// <auto-generated />
using Kariyer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kariyer.Migrations
{
    [DbContext(typeof(KariyerDbContext))]
    partial class KariyerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kariyer.Models.BasvuruSahibi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ToplamTecrube")
                        .HasColumnType("int");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BasvuruSahibis");
                });

            modelBuilder.Entity("Kariyer.Models.Deneyim", b =>
                {
                    b.Property<int>("DeneyimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BSId")
                        .HasColumnType("int");

                    b.Property<string>("CalismaTanimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalismaYili")
                        .HasColumnType("int");

                    b.Property<string>("FirmaAdlari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeneyimId");

                    b.HasIndex("BSId");

                    b.ToTable("Deneyims");
                });

            modelBuilder.Entity("Kariyer.Models.Deneyim", b =>
                {
                    b.HasOne("Kariyer.Models.BasvuruSahibi", "BasvuruSahibi")
                        .WithMany()
                        .HasForeignKey("BSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasvuruSahibi");
                });
#pragma warning restore 612, 618
        }
    }
}
